logInfo("movie.script", "movie script")

		
gKeuken?.members.forEach(light | sendCommand(light, OFF))
//gWoonkamer.members.forEach(light | sendCommand(light, ON))


gSleeping.members.forEach(light| sendCommand(light, OFF));

//sendCommand(onkyoPower, ON);
//sendCommand(onkyoSrcAux, ON);
		
sendCommand(Kast_led, 10);		
		
//postUpdate(Scene_General, 2)
if (!Scene_General.state.equals(2)) postUpdate(Scene_General, 2);